[versions]
dokka-ver = "2.0.0"
jetbrains-annotations = "26.0.0"
jspecify-version = "1.0.0"
junit-version = "6.0.1"
mockbukkit-version = "4.98.0"
mockito-version = "5.21.0"
paper-api-version = "1.21.10-R0.1-SNAPSHOT" # Stuck on base 1.21.10 for mockbukkit
# Plugins
kotlin-jvm-ver = "2.3.0"
shadow-ver = "9.3.0"
spotless-ver = "8.1.0"
# Plugins End

[libraries]
dokka = { module = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin", version.ref = "dokka-ver" }
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka-ver" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify-version" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-version" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-jvm-ver" }
mockbukkit = { module = "org.mockbukkit.mockbukkit:mockbukkit-v1.21", version.ref = "mockbukkit-version" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito-version" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api-version" }
spotless = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless-ver" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm-ver" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-ver" }